const sampleCode = `def find_maximum(numbers):
    maximum = numbers[0]
    for number in numbers:
        if number > maximum:
            maximum = number
    print("Maximum:", maximum)
    return maximum

values = [3, 8, 2, 10, 5]
result = find_maximum(values)
print("Result:", result)`;

const state = { trace: null, stepIndex: 0, playing: false, timer: null, playSpeed: 1, voiceEnabled: true, ttsAvailable: false, recognitionConstructor: null, recognition: null, recognitionActive: false, voiceBaseAnswer: "", voiceFinalTranscript: "", structurePositions: {} };
const PLAYBACK_BASE_DELAY = 1000;
const mentorAccessToken = localStorage.getItem("mentor_access_token");
const mentorSessionId = localStorage.getItem("mentor_workspace_session_id");
function mentorUserId() {
  if (!mentorAccessToken) return null;
  try {
    const payload = mentorAccessToken.split(".")[1].replace(/-/g, "+").replace(/_/g, "/");
    return JSON.parse(atob(payload)).sub || null;
  } catch (_) { return null; }
}
const activeUserId = mentorUserId();
const authHeaders = mentorAccessToken
  ? { Authorization: `Bearer ${mentorAccessToken}` }
  : { "X-API-Key": "dev-api-key", "X-User-ID": "ui-user" };
const $ = (id) => document.getElementById(id);
function showToast(message) { const toast = $("toast"); toast.textContent = message; toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 2600); }
function escapeHtml(value) { return String(value).replace(/[&<>"']/g, (c) => ({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[c])); }
function syncEditor() { const lines = $("source-code").value.split("\n"); $("line-numbers").innerHTML = lines.map((_, i) => `<div>${i + 1}</div>`).join(""); $("code-highlight").innerHTML = lines.map((line, i) => `<div data-line="${i + 1}">${escapeHtml(line) || " "}</div>`).join(""); }
function renderNodes() { const count = state.trace?.steps.length || 0; $("timeline-nodes").innerHTML = count ? state.trace.steps.map((step, i) => `<button class="timeline-node ${i < state.stepIndex ? "done" : ""} ${i === state.stepIndex ? "active" : ""}" data-index="${i}" title="Step ${step.step_number}: ${step.event_type}"></button>`).join("") : ""; $("timeline-nodes").querySelectorAll("button").forEach((node) => node.addEventListener("click", () => selectStep(Number(node.dataset.index)))); $("timeline-progress").style.width = count > 1 ? `${(state.stepIndex / (count - 1)) * 100}%` : "0%"; }
function selectStep(index) {
  if (!state.trace) return;
  state.stepIndex = Math.max(0, Math.min(index, state.trace.steps.length - 1));
  const step = state.trace.steps[state.stepIndex];
  $("step-counter").textContent = `${String(step.step_number).padStart(2, "0")} / ${String(state.trace.steps.length).padStart(2, "0")}`;
  $("event-badge").textContent = step.event_type.replaceAll("_", " "); $("line-reference").textContent = step.line_number ? `line ${step.line_number}` : "runtime";
  $("current-statement").textContent = step.error ? `Error: ${step.error}` : (step.executed_code || (step.event_type === "EXCEPTION" ? "An exception interrupted execution." : "Function frame transition"));
  $("ai-explanation").textContent = "Loading step explanation…";
  document.querySelectorAll(".code-highlight [data-line]").forEach((line) => line.classList.toggle("active-line", Number(line.dataset.line) === step.line_number));
  const vars = Object.entries(step.locals || {}); $("variable-count").textContent = vars.length; $("variables-content").classList.toggle("empty-state", vars.length === 0); $("variables-content").innerHTML = vars.length ? vars.map(([name, value]) => `<div class="variable-row"><span class="variable-name">${escapeHtml(name)}</span><span class="variable-value">${escapeHtml(JSON.stringify(value))}</span></div>`).join("") : "No local variables in this frame"; renderStructure(step, state.trace.steps[state.stepIndex - 1]);
  $("stack-content").innerHTML = step.call_stack?.length ? step.call_stack.slice().reverse().map((frame) => `<div class="stack-frame">${escapeHtml(frame)}()</div>`).join("") : `<div class="empty-state">No active frames</div>`; $("console-output").textContent = step.stdout ? `$ ${step.stdout}` : "$ No output yet"; renderNodes(); loadExplanation(step.step_number);
}
async function loadExplanation(stepNumber) { try { const response = await fetch(`/visualization/${state.trace.id}/steps/${stepNumber}`, { headers: authHeaders }); if (!response.ok) return; const data = await response.json(); if (state.trace.steps[state.stepIndex]?.step_number === stepNumber) { $("ai-explanation").textContent = data.annotation.explanation; $("ai-provider").textContent = data.annotation.provider === "groq" ? "GROQ AI EXPLANATION" : "LOCAL FALLBACK · NO GROQ RESPONSE"; } } catch (_) { $("ai-provider").textContent = "EXPLANATION UNAVAILABLE"; } }
async function apiErrorMessage(response) { try { const payload = await response.json(); const detail = payload?.detail; if (Array.isArray(detail)) return detail.map((item) => item.msg || JSON.stringify(item)).join("; "); if (detail) return String(detail); } catch (_) { /* The server may have returned a non-JSON error page. */ } return `Request failed (${response.status})`; }
function renderSummary() { const summary = state.trace.summary; $("summary-flow").textContent = summary?.algorithm_flow || "Run a trace to generate an overview."; $("metric-steps").textContent = summary?.execution_length ?? "—"; $("metric-functions").textContent = summary ? `${(summary.recursion_summary.match(/\d+/) || [0])[0]} calls` : "—"; $("metric-output").textContent = summary?.final_output?.trim() ? "Captured" : "None"; }
function renderScoreChart(points) { const container = $("score-chart"); if (!points.length) { container.innerHTML = '<div class="empty-state">Complete an interview to see score trends.</div>'; return; } const width = 540; const height = 170; const padding = 28; const values = points.map((point) => Number(point.score) || 0); const min = Math.min(...values); const max = Math.max(...values); const range = Math.max(1, max - min); const coordinates = values.map((value, index) => ({ x: padding + (index * (width - padding * 2)) / Math.max(1, values.length - 1), y: height - padding - ((value - min) / range) * (height - padding * 2) })); const polyline = coordinates.map((point) => `${point.x},${point.y}`).join(" "); const dots = coordinates.map((point, index) => `<circle class="chart-dot" cx="${point.x}" cy="${point.y}" r="4"><title>${escapeHtml(points[index].date)} · ${escapeHtml(points[index].score)}</title></circle>`).join(""); container.innerHTML = `<svg viewBox="0 0 ${width} ${height}" role="img" aria-label="Interview score trend"><line class="chart-grid" x1="${padding}" y1="${padding}" x2="${width - padding}" y2="${padding}"></line><line class="chart-grid" x1="${padding}" y1="${height - padding}" x2="${width - padding}" y2="${height - padding}"></line><polyline class="chart-line" points="${polyline}"></polyline>${dots}<text x="${padding}" y="${height - 7}">${escapeHtml(points[0].date)}</text><text x="${width - padding}" y="${height - 7}" text-anchor="end">${escapeHtml(points[points.length - 1].date)}</text><text x="${padding}" y="${padding - 8}">${escapeHtml(String(max))}</text><text x="${padding}" y="${height - padding - 8}">${escapeHtml(String(min))}</text></svg>`; }
function renderLanguageChart(languages) { const container = $("language-chart"); const entries = Object.entries(languages || {}).sort((a, b) => b[1] - a[1]); if (!entries.length) { container.innerHTML = '<div class="empty-state">Run a trace or interview to see language activity.</div>'; return; } const maximum = Math.max(...entries.map(([, count]) => count)); container.innerHTML = entries.map(([language, count]) => `<div class="analytics-bar-row"><span>${escapeHtml(language)}</span><div class="analytics-bar-track"><div class="analytics-bar-fill" style="width:${(count / maximum) * 100}%"></div></div><strong>${count}</strong></div>`).join(""); }
function renderActivity(events) { const container = $("activity-list"); if (!events?.length) { container.innerHTML = '<div class="empty-state">No learning events yet.</div>'; return; } container.innerHTML = events.map((event) => { const date = new Date(event.timestamp); return `<div class="activity-row"><span class="activity-type">${escapeHtml(event.event_type.replaceAll("_", " "))}</span><span class="activity-source">${escapeHtml(event.source)}</span><span class="activity-time">${escapeHtml(Number.isNaN(date.getTime()) ? event.timestamp : date.toLocaleString())}</span></div>`; }).join(""); }
function renderRecommendations(items) { const container = $("recommendations-list"); if (!items?.length) { container.innerHTML = '<div class="empty-state">Complete activity to get recommendations.</div>'; return; } container.innerHTML = items.map((item) => `<div class="recommendation-item"><span aria-hidden="true">✦</span>${escapeHtml(item)}</div>`).join(""); }
function renderAnalytics(data) { const totals = data.totals || {}; const snapshot = data.snapshot || {}; const progress = data.progress || {}; $("analytics-interviews").textContent = totals.completed_interviews ?? 0; $("analytics-problems").textContent = totals.total_problems_solved ?? 0; $("analytics-score").textContent = snapshot.average_score == null ? "—" : snapshot.average_score; $("analytics-active-days").textContent = progress.active_days_30d ?? 0; $("analytics-score-change").textContent = progress.score_change == null ? "No trend" : `${progress.score_change >= 0 ? "+" : ""}${progress.score_change}`; $("analytics-event-count").textContent = `${totals.total_events ?? 0} events`; $("analytics-status").textContent = snapshot.last_active ? `Last active ${new Date(snapshot.last_active).toLocaleString()}` : "No activity yet"; renderRecommendations(data.recommendations || []); renderScoreChart(data.scores_by_date || []); renderLanguageChart(data.language_distribution || {}); renderActivity(data.recent_activity || []); }
async function loadAnalytics() { $("analytics-status").textContent = "Loading your learning activity…"; try { const response = await fetch("/analytics/me", { headers: authHeaders }); if (!response.ok) throw new Error(await response.text()); renderAnalytics(await response.json()); } catch (error) { $("analytics-status").textContent = "Analytics unavailable — run the API and try again."; console.error(error); } }
async function downloadAnalytics(format) { try { const response = await fetch(`/analytics/me/export?format=${encodeURIComponent(format)}`, { headers: authHeaders }); if (!response.ok) throw new Error(await response.text()); const blob = await response.blob(); const url = URL.createObjectURL(blob); const link = document.createElement("a"); link.href = url; link.download = `analytics-export.${format}`; document.body.appendChild(link); link.click(); link.remove(); URL.revokeObjectURL(url); showToast(`${format.toUpperCase()} export downloaded`); } catch (error) { showToast("Could not export analytics"); console.error(error); } }
function isSnapshotRef(value) { return value && typeof value === "object" && Number.isInteger(value.__ref__); }
function isPrimitiveSnapshot(value) { return value === null || ["string", "number", "boolean"].includes(typeof value); }
function structureValues(step) { return Object.entries({ ...(step?.globals || {}), ...(step?.locals || {}) }); }
function collectStructureGraph(step) {
  const graph = { nodes: new Map(), edges: [], edgeKeys: new Set(), roots: new Set(), arrays: [] };
  const visit = (value, rootName = null) => {
    if (isSnapshotRef(value)) {
      const id = String(value.__ref__); let node = graph.nodes.get(id);
      if (!node) { node = { id, type: value.__type__ || "Object", attrs: {}, labels: new Set() }; graph.nodes.set(id, node); }
      if (rootName) { graph.roots.add(id); node.labels.add(rootName); }
      if (!value.attrs) return;
      node.type = value.__type__ || node.type; node.attrs = value.attrs;
      Object.entries(value.attrs).forEach(([attribute, child]) => {
        if (isSnapshotRef(child)) { const edgeKey = `${id}:${attribute}:${child.__ref__}`; if (!graph.edgeKeys.has(edgeKey)) { graph.edgeKeys.add(edgeKey); graph.edges.push({ from: id, to: String(child.__ref__), label: attribute }); } visit(child); }
        else if (Array.isArray(child)) child.forEach((item) => visit(item));
        else if (child && typeof child === "object") Object.values(child).forEach((item) => visit(item));
      });
      return;
    }
    if (Array.isArray(value)) value.forEach((item) => visit(item));
    else if (value && typeof value === "object") Object.values(value).forEach((item) => visit(item));
  };
  structureValues(step).forEach(([name, value]) => { if (isSnapshotRef(value)) visit(value, name); else if (Array.isArray(value) && value.every(isPrimitiveSnapshot)) graph.arrays.push({ name, values: value }); });
  return graph;
}
function structureShape(graph) { const nodes = [...graph.nodes.values()]; if (nodes.some((node) => ["left", "right"].some((name) => isSnapshotRef(node.attrs[name])) || Object.keys(node.attrs).filter((name) => /left|right|child/i.test(name) && isSnapshotRef(node.attrs[name])).length >= 2)) return "TREE"; if (nodes.some((node) => isSnapshotRef(node.attrs.next) || Object.keys(node.attrs).some((name) => /next/i.test(name) && isSnapshotRef(node.attrs[name])))) return "LINKED LIST"; return "GRAPH"; }
function structureRoots(graph) { const incoming = new Set(graph.edges.map((edge) => edge.to)); const roots = [...graph.roots].filter((id) => !incoming.has(id)); return roots.length ? roots : [...graph.roots].slice(0, 1); }
function layoutStructure(graph, shape) {
  const positions = new Map(); let width = 700; const nodes = [...graph.nodes.values()]; let rowCount = 1;
  if (shape === "TREE") {
    const levels = new Map(); const visited = new Set(); const queue = structureRoots(graph).map((id) => ({ id, depth: 0 }));
    while (queue.length) { const current = queue.shift(); if (visited.has(current.id)) continue; visited.add(current.id); if (!levels.has(current.depth)) levels.set(current.depth, []); levels.get(current.depth).push(current.id); const node = graph.nodes.get(current.id); ["left", "right"].forEach((name) => { const child = node?.attrs?.[name]; if (isSnapshotRef(child)) queue.push({ id: String(child.__ref__), depth: current.depth + 1 }); }); }
    nodes.forEach((node) => { if (!visited.has(node.id)) { const depth = levels.size; if (!levels.has(depth)) levels.set(depth, []); levels.get(depth).push(node.id); } });
    const widestLevel = Math.max(1, ...[...levels.values()].map((ids) => ids.length)); width = Math.max(700, widestLevel * 150); rowCount = levels.size;
    for (const [depth, ids] of levels) ids.forEach((id, index) => positions.set(id, { x: width * (index + 1) / (ids.length + 1), y: 42 + depth * 78 }));
  } else if (shape === "LINKED LIST") {
    const ordered = []; const visited = new Set(); let current = structureRoots(graph)[0];
    while (current && !visited.has(current)) { visited.add(current); ordered.push(current); const next = graph.nodes.get(current)?.attrs?.next; current = isSnapshotRef(next) ? String(next.__ref__) : null; }
    nodes.forEach((node) => { if (!visited.has(node.id)) ordered.push(node.id); }); rowCount = Math.ceil(ordered.length / 5); ordered.forEach((id, index) => positions.set(id, { x: 80 + (index % 5) * 140, y: 55 + Math.floor(index / 5) * 90 }));
  } else { rowCount = Math.ceil(nodes.length / 4); nodes.forEach((node, index) => positions.set(node.id, { x: 80 + (index % 4) * 170, y: 48 + Math.floor(index / 4) * 90 })); }
  return { positions, width, height: Math.max(220, rowCount * 90 + 70) };
}
function structureLabel(node) { const value = node.attrs?.value ?? node.attrs?.data ?? node.attrs?.key; return value === undefined ? node.type : `${node.type}: ${JSON.stringify(value)}`; }
function changedStructureRefs(current, previous) { const active = new Set(); const currentNodes = current.nodes; const previousNodes = previous?.nodes || new Map(); currentNodes.forEach((node, id) => { if (!previousNodes.has(id) || JSON.stringify(node.attrs) !== JSON.stringify(previousNodes.get(id).attrs)) active.add(id); }); if (!active.size) structureRoots(current).forEach((id) => active.add(id)); return active; }
function renderArrayStructure(arrayInfo) { const width = Math.max(460, arrayInfo.values.length * 92 + 40); const cells = arrayInfo.values.map((value, index) => `<g class="structure-array-cell"><rect x="${20 + index * 92}" y="62" width="82" height="48" rx="6"></rect><text x="${61 + index * 92}" y="91" text-anchor="middle">${escapeHtml(JSON.stringify(value))}</text><text class="structure-index" x="${61 + index * 92}" y="128" text-anchor="middle">${index}</text></g>`).join(""); $("structure-svg").setAttribute("viewBox", `0 0 ${width} 160`); $("structure-svg").innerHTML = cells; $("structure-shape").textContent = `ARRAY · ${arrayInfo.name}`; $("structure-empty").classList.add("hidden"); }
function renderStructure(step, previousStep) {
  const current = collectStructureGraph(step); const previous = previousStep ? collectStructureGraph(previousStep) : null; const arrayInfo = current.arrays[0];
  if (!current.nodes.size && arrayInfo) return renderArrayStructure(arrayInfo);
  if (!current.nodes.size) { $("structure-svg").innerHTML = ""; $("structure-empty").textContent = "Run a trace with an object or primitive array to see its structure."; $("structure-empty").classList.remove("hidden"); $("structure-shape").textContent = "—"; return; }
  const shape = structureShape(current); const layout = layoutStructure(current, shape); const active = changedStructureRefs(current, previous); const nodeWidth = 112; const nodeHeight = 48; const edgeSvg = current.edges.map((edge) => { const from = layout.positions.get(edge.from); const to = layout.positions.get(edge.to); if (!from || !to) return ""; return `<line class="structure-edge" x1="${from.x}" y1="${from.y + nodeHeight / 2}" x2="${to.x}" y2="${to.y - nodeHeight / 2}" marker-end="url(#structure-arrow)"></line>`; }).join(""); const nodeSvg = [...current.nodes.values()].map((node) => { const position = layout.positions.get(node.id); if (!position) return ""; const previousPosition = state.structurePositions[node.id] || position; const animation = previousPosition.x !== position.x || previousPosition.y !== position.y ? `<animateTransform attributeName="transform" type="translate" from="${previousPosition.x} ${previousPosition.y}" to="${position.x} ${position.y}" dur="240ms" fill="freeze"></animateTransform>` : ""; return `<g class="structure-node ${active.has(node.id) ? "active" : ""}" transform="translate(${position.x} ${position.y})"><rect x="${-nodeWidth / 2}" y="${-nodeHeight / 2}" width="${nodeWidth}" height="${nodeHeight}" rx="7"></rect><text class="structure-node-type" x="0" y="-5" text-anchor="middle">${escapeHtml(node.type)}</text><text class="structure-node-value" x="0" y="14" text-anchor="middle">${escapeHtml(structureLabel(node).replace(`${node.type}: `, "").slice(0, 18))}</text>${animation}</g>`; }).join(""); $("structure-svg").setAttribute("viewBox", `0 0 ${layout.width} ${layout.height}`); $("structure-svg").innerHTML = `<defs><marker id="structure-arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8 Z"></path></marker></defs>${edgeSvg}${nodeSvg}`; $("structure-shape").textContent = shape; $("structure-empty").classList.add("hidden"); state.structurePositions = Object.fromEntries([...layout.positions.entries()]); }
async function runTrace() {
  const code = $("source-code").value.trim(); if (!code) return showToast("Add some Python code first"); stopPlayback(); const button = $("run-button"); button.disabled = true; button.textContent = "Running…"; $("source-status").textContent = "Tracing execution…";
  try { const created = await fetch("/visualization/trace", { method: "POST", headers: { ...authHeaders, "Content-Type": "application/json" }, body: JSON.stringify({ language: "python", source_code: code }) }); if (!created.ok) throw new Error(await apiErrorMessage(created)); const { trace_id } = await created.json(); const response = await fetch(`/visualization/${trace_id}`, { headers: authHeaders }); if (!response.ok) throw new Error(await apiErrorMessage(response)); state.trace = await response.json(); state.stepIndex = 0; state.structurePositions = {}; $("trace-id").textContent = trace_id; $("source-status").textContent = `${state.trace.steps.length} execution steps captured`; renderSummary(); selectStep(0); showToast("Trace ready to replay"); } catch (error) { const message = error instanceof TypeError ? "Could not reach the API — is the server running?" : `Trace rejected: ${error.message}`; showToast(message); $("source-status").textContent = message; console.error(error); } finally { button.disabled = false; button.textContent = "▶ Run trace"; }
}
function stopPlayback() { if (state.timer !== null) { clearInterval(state.timer); state.timer = null; } state.playing = false; $("play-button").textContent = "▶"; }
function startPlaybackTimer() { if (!state.trace) return; if (state.timer !== null) clearInterval(state.timer); state.timer = setInterval(() => { if (state.stepIndex >= state.trace.steps.length - 1) return stopPlayback(); selectStep(state.stepIndex + 1); }, PLAYBACK_BASE_DELAY / state.playSpeed); }
function setPlaybackSpeed(speed) { state.playSpeed = Number(speed); document.querySelectorAll("[data-play-speed]").forEach((button) => { const active = Number(button.dataset.playSpeed) === state.playSpeed; button.classList.toggle("active", active); button.setAttribute("aria-pressed", String(active)); }); if (state.playing) startPlaybackTimer(); }
function togglePlay() { if (!state.trace) return; if (state.playing) stopPlayback(); else { state.playing = true; $("play-button").textContent = "Ⅱ"; startPlaybackTimer(); } }
function speakInterviewMessage(text) { if (!state.voiceEnabled || !state.ttsAvailable || !text?.trim()) return; const utterance = new SpeechSynthesisUtterance(text); window.speechSynthesis.speak(utterance); }
function updateVoiceToggle() { const button = $("interview-voice-toggle"); if (!button) return; button.textContent = state.voiceEnabled ? "🔊 Voice on" : "🔇 Voice off"; button.setAttribute("aria-pressed", String(state.voiceEnabled)); }
function updateRecognitionUI() { const button = $("voice-input-button"); const indicator = $("voice-recording-indicator"); if (!button) return; button.classList.toggle("recording", state.recognitionActive); button.textContent = state.recognitionActive ? "■" : "🎙"; button.setAttribute("aria-label", state.recognitionActive ? "Stop voice input" : "Start voice input"); indicator?.classList.toggle("hidden", !state.recognitionActive); }
function stopVoiceInput() { if (state.recognition) { try { state.recognition.stop(); } catch (_) {} state.recognition = null; } state.recognitionActive = false; updateRecognitionUI(); if (state.ttsAvailable) window.speechSynthesis.cancel(); }
function toggleInterviewVoice() { state.voiceEnabled = !state.voiceEnabled; if (!state.voiceEnabled && state.ttsAvailable) window.speechSynthesis.cancel(); updateVoiceToggle(); }
function updateVoiceAnswer(interimTranscript = "") { const parts = [state.voiceBaseAnswer.trimEnd(), state.voiceFinalTranscript.trim(), interimTranscript.trim()].filter(Boolean); $("interview-answer").value = parts.join(" "); }
function startVoiceInput() {
  if (!state.recognitionConstructor) return;
  if (state.recognitionActive) return stopVoiceInput();
  if (state.ttsAvailable) window.speechSynthesis.cancel();
  const recognition = new state.recognitionConstructor(); state.recognition = recognition; state.voiceBaseAnswer = $("interview-answer").value.trimEnd(); state.voiceFinalTranscript = "";
  recognition.continuous = true; recognition.interimResults = true; recognition.lang = navigator.language || "en-US";
  recognition.onstart = () => { state.recognitionActive = true; updateRecognitionUI(); };
  recognition.onresult = (event) => { let interim = ""; for (let index = event.resultIndex; index < event.results.length; index += 1) { const transcript = event.results[index][0].transcript; if (event.results[index].isFinal) state.voiceFinalTranscript += `${transcript} `; else interim += transcript; } updateVoiceAnswer(interim); };
  recognition.onerror = (event) => { if (event.error !== "aborted") showToast(`Voice input unavailable: ${event.error}`); };
  recognition.onend = () => { state.recognition = null; state.recognitionActive = false; updateRecognitionUI(); };
  try { recognition.start(); } catch (error) { state.recognition = null; state.recognitionActive = false; updateRecognitionUI(); showToast("Could not start voice input"); console.error(error); }
}
function ensureVoiceControls() {
  const header = document.querySelector("#interview-view .interview-chat .panel-header"); const answerBox = $("interview-answer")?.closest(".answer-box");
  if (header && !$("interview-voice-toggle")) { const toggle = document.createElement("button"); toggle.id = "interview-voice-toggle"; toggle.className = "voice-toggle secondary-button"; toggle.type = "button"; toggle.title = "Toggle spoken interviewer questions"; header.appendChild(toggle); }
  if (!answerBox || $("voice-input-button")) return;
  const answer = $("interview-answer"); const inputRow = document.createElement("div"); inputRow.className = "answer-input-row"; answer.parentNode.insertBefore(inputRow, answer); inputRow.appendChild(answer);
  const mic = document.createElement("button"); mic.id = "voice-input-button"; mic.className = "voice-button"; mic.type = "button"; mic.textContent = "🎙"; mic.title = "Dictate answer"; inputRow.appendChild(mic);
  const note = document.createElement("p"); note.id = "voice-input-note"; note.className = "voice-input-note hidden"; answerBox.insertBefore(note, answerBox.querySelector(".answer-actions"));
  const indicator = document.createElement("span"); indicator.id = "voice-recording-indicator"; indicator.className = "voice-recording-indicator hidden"; indicator.innerHTML = '<span class="status-dot"></span> Listening…'; answerBox.querySelector(".answer-actions").prepend(indicator);
}
function initialiseVoiceFeatures() {
  state.ttsAvailable = "speechSynthesis" in window && "SpeechSynthesisUtterance" in window;
  state.recognitionConstructor = window.SpeechRecognition || window.webkitSpeechRecognition || null;
  const toggle = $("interview-voice-toggle"); const mic = $("voice-input-button"); const note = $("voice-input-note");
  if (!state.ttsAvailable) toggle?.classList.add("hidden"); else toggle?.addEventListener("click", toggleInterviewVoice);
  if (!state.recognitionConstructor) { mic?.classList.add("hidden"); note.textContent = "Voice input isn't supported in this browser — type your answer."; note.classList.remove("hidden"); } else mic?.addEventListener("click", startVoiceInput);
  updateVoiceToggle(); updateRecognitionUI();
}
function setView(view) { if (view !== "interview") stopVoiceInput(); document.querySelectorAll(".view").forEach((el) => el.classList.add("hidden")); $(`${view}-view`).classList.remove("hidden"); $("page-title").textContent = view === "lab" ? "Execution Lab" : view === "interview" ? "Interview Coach" : "Analytics"; document.querySelectorAll(".nav-item").forEach((item) => item.classList.toggle("active", item.dataset.view === view)); if (view === "analytics") loadAnalytics(); }
$("source-code").value = sampleCode; syncEditor(); setPlaybackSpeed(state.playSpeed); ensureVoiceControls(); initialiseVoiceFeatures(); $("source-code").addEventListener("input", syncEditor); $("run-button").addEventListener("click", runTrace); $("play-button").addEventListener("click", togglePlay); $("next-button").addEventListener("click", () => selectStep(state.stepIndex + 1)); $("prev-button").addEventListener("click", () => selectStep(state.stepIndex - 1)); $("restart-button").addEventListener("click", () => selectStep(0)); document.querySelectorAll("[data-play-speed]").forEach((button) => button.addEventListener("click", () => setPlaybackSpeed(button.dataset.playSpeed))); document.querySelectorAll("[data-view]").forEach((item) => item.addEventListener("click", () => setView(item.dataset.view))); window.addEventListener("beforeunload", stopVoiceInput); document.addEventListener("keydown", (event) => { if (event.target.tagName === "TEXTAREA") return; if (event.key === "ArrowRight") selectStep(state.stepIndex + 1); if (event.key === "ArrowLeft") selectStep(state.stepIndex - 1); if (event.key === " ") { event.preventDefault(); togglePlay(); } });
const embeddedParams = new URLSearchParams(window.location.search);
const embeddedView = embeddedParams.get("view");
if (["lab", "interview", "analytics"].includes(embeddedView)) setView(embeddedView);
if (embeddedParams.get("merged") === "1") document.querySelector(".sidebar")?.remove();
$("source-code").value = ""; syncEditor(); $("load-example-button").addEventListener("click", () => { $("source-code").value = sampleCode; syncEditor(); $("source-status").textContent = "Example loaded — edit it freely"; });

let interviewId = null;
function addInterviewMessage(role, content) { const box = $("interview-messages"); if (box.querySelector(".empty-state")) box.innerHTML = ""; const item = document.createElement("div"); item.className = `message ${role === "AI" ? "ai" : "user"}`; item.innerHTML = `<span class="message-label">${role}</span>${escapeHtml(content).replace(/\n/g, "<br>")}`; box.appendChild(item); box.scrollTop = box.scrollHeight; if (role === "AI") speakInterviewMessage(content); }
async function startInterview() {
  const payload = { context: { submission_id: mentorSessionId || `ui-${Date.now()}`, user_id: activeUserId || "ui-user", problem_title: $("interview-title").value, problem_description: $("interview-description").value, language: $("interview-language").value, code: $("interview-code").value, execution_result: $("interview-execution").value, hint_count: Number($("interview-hints").value), attempt_count: Number($("interview-attempts").value), difficulty: $("interview-difficulty").value }, style: "Friendly" };
  try { const response = await fetch("/interview/start", { method: "POST", headers: { ...authHeaders, "Content-Type": "application/json" }, body: JSON.stringify(payload) }); if (!response.ok) throw new Error(await response.text()); const data = await response.json(); interviewId = data.interview_id; $("interview-messages").innerHTML = ""; $("interview-state").textContent = "WAITING FOR ANSWER"; addInterviewMessage("AI", data.first_question); showToast("Interview started"); } catch (error) { showToast("Could not start interview"); console.error(error); }
}
async function submitInterviewAnswer() { if (!interviewId) return showToast("Start an interview first"); const answer = $("interview-answer").value.trim(); if (!answer) return showToast("Write an answer first"); stopVoiceInput(); try { const response = await fetch(`/interview/${interviewId}/answer`, { method: "POST", headers: { ...authHeaders, "Content-Type": "application/json" }, body: JSON.stringify({ answer }) }); if (!response.ok) throw new Error(await response.text()); const data = await response.json(); addInterviewMessage("USER", answer); $("interview-answer").value = ""; const score = data.evaluation; addInterviewMessage("AI", `Evaluation — technical ${score.technical_accuracy}/10, communication ${score.communication}/10, complexity ${score.complexity_understanding}/10, edge cases ${score.edge_case_reasoning}/10. ${score.feedback}`); addInterviewMessage("AI", data.next_question || "That completes the planned questions. You can finish the interview now."); $("interview-state").textContent = data.next_question ? "FOLLOW-UP READY" : "COMPLETED"; if (!data.next_question) stopVoiceInput(); } catch (error) { showToast("Could not submit answer"); console.error(error); } }
async function finishInterview() { if (!interviewId) return showToast("Start an interview first"); stopVoiceInput(); try { const response = await fetch(`/interview/${interviewId}/finish`, { method: "POST", headers: authHeaders }); if (!response.ok) throw new Error(await response.text()); const report = await response.json(); $("interview-state").textContent = "REPORT READY"; const panel = $("interview-report"); panel.classList.remove("hidden"); panel.innerHTML = `<h2>Interview report</h2><p>${escapeHtml(report.summary)}</p><div class="report-grid"><div><span class="section-kicker">OVERALL SCORE</span><strong>${report.overall_score}/10</strong></div><div><span class="section-kicker">STRENGTHS</span><p>${escapeHtml(report.strengths.join(", "))}</p></div><div><span class="section-kicker">NEXT TOPICS</span><p>${escapeHtml(report.recommended_topics.join(", "))}</p></div></div>`; } catch (error) { showToast("Could not finish interview"); console.error(error); } }
$("start-interview").addEventListener("click", startInterview); $("submit-answer").addEventListener("click", submitInterviewAnswer); $("finish-interview").addEventListener("click", finishInterview); $("analytics-refresh").addEventListener("click", loadAnalytics); $("analytics-export-json").addEventListener("click", () => downloadAnalytics("json")); $("analytics-export-csv").addEventListener("click", () => downloadAnalytics("csv"));
